"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Rule = { id:string; source_type:string; match_field:string; match_operator:string; match_value:string; transaction_type:string; category_l1:string|null; category_l2:string|null; fixed_variable:string|null; essential_optional:string|null; priority:number; is_active:boolean };
type Category = { id:string; parent_id:string|null; name:string; is_active:boolean };
const TYPES = [["EXPENSE","지출"],["INCOME","수입"],["CARD_SETTLEMENT","카드대금 납부"],["DEBT_PAYMENT","대출 상환"],["INVESTMENT_TRANSFER","투자금 이체"],["INTERNAL_TRANSFER","계좌 간 이동"],["REFUND","환불"],["REIMBURSEMENT","비용 정산"],["OTHER","기타"]];

export default function RulesPage() {
  const [rules,setRules]=useState<Rule[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [search,setSearch]=useState(""); const [selectedId,setSelectedId]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{const [rr,cr]=await Promise.all([fetch("/api/finance/rules",{cache:"no-store"}),fetch("/api/finance/categories",{cache:"no-store"})]); const rd=await rr.json(); const cd=await cr.json(); if(!rr.ok||!rd.success) throw new Error(rd.error??"규칙을 불러오지 못했습니다."); setRules(rd.rules??[]); if(cr.ok&&cd.success)setCategories(cd.categories??[]);},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{load().catch((reason)=>setError(reason.message));},0);return()=>window.clearTimeout(timer);},[load]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase(); return q?rules.filter((rule)=>[rule.match_value,rule.category_l1,rule.category_l2].some((v)=>v?.toLowerCase().includes(q))):rules;},[rules,search]);
  const selected=rules.find((rule)=>rule.id===selectedId)??null;
  async function save(rule:Rule){setError(null); const response=await fetch("/api/finance/rules",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:rule.id,sourceType:rule.source_type,matchField:rule.match_field,matchOperator:rule.match_operator,matchValue:rule.match_value,transactionType:rule.transaction_type,categoryL1:rule.category_l1,categoryL2:rule.category_l2,fixedVariable:rule.fixed_variable,essentialOptional:rule.essential_optional,priority:rule.priority,isActive:rule.is_active})}); const data=await response.json(); if(!response.ok||!data.success){setError(data.error??"규칙을 저장하지 못했습니다.");return;} await load(); setSelectedId(null);}
  return <main className="min-h-screen bg-gray-50 p-4 md:p-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-gray-500">설정</p><h1 className="mt-1 text-3xl font-bold">자동분류 규칙</h1><p className="mt-2 text-sm text-gray-500">앞으로 들어오는 거래에 적용되는 기준을 검토하고 안전하게 끌 수 있습니다.</p></div><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="거래처·카테고리 검색" className="w-full rounded-lg border border-gray-300 px-3 py-2 sm:w-72" /></header>
  {error&&<div className="mt-5 border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_390px]"><section className="overflow-hidden border border-gray-200 bg-white"><div className="border-b border-gray-200 px-5 py-4 text-sm text-gray-500">총 {filtered.length}개</div>{filtered.length===0?<p className="p-10 text-center text-sm text-gray-500">등록된 규칙이 없습니다.</p>:filtered.map((rule)=><button key={rule.id} onClick={()=>setSelectedId(rule.id)} className={`flex w-full items-center gap-4 border-b border-gray-100 px-5 py-4 text-left last:border-0 hover:bg-gray-50 ${selectedId===rule.id?"bg-gray-50":""}`}><span className={`h-2.5 w-2.5 rounded-full ${rule.is_active?"bg-emerald-500":"bg-gray-300"}`} /><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{rule.match_value}</strong><span className="mt-1 block text-xs text-gray-500">{rule.source_type==="BANK"?"은행":"카드"} · {rule.match_field==="COUNTERPARTY"?"거래처":"내용"} {rule.match_operator==="EXACT"?"정확히 일치":"문구 포함"}</span></span><span className="text-right text-sm text-gray-600">{TYPES.find(([v])=>v===rule.transaction_type)?.[1]}<small className="block text-gray-400">{[rule.category_l1,rule.category_l2].filter(Boolean).join(" / ")||"미분류"}</small></span></button>)}</section>
  <aside className="lg:sticky lg:top-6 lg:self-start">{selected?<RuleEditor key={selected.id} initial={selected} categories={categories} save={save} close={()=>setSelectedId(null)} />:<div className="border border-dashed border-gray-300 bg-white p-8 text-center text-sm text-gray-500">규칙을 선택하면 상세 설정을 편집할 수 있습니다.</div>}</aside></div></div></main>;
}

function RuleEditor({initial,categories,save,close}:{initial:Rule;categories:Category[];save:(rule:Rule)=>Promise<void>;close:()=>void}){const [rule,setRule]=useState(initial); const roots=categories.filter((c)=>!c.parent_id&&c.is_active); const root=roots.find((c)=>c.name===rule.category_l1); const children=categories.filter((c)=>c.parent_id===root?.id&&c.is_active); const field=(key:keyof Rule,value:string|number|boolean|null)=>setRule((old)=>({...old,[key]:value})); return <div className="border border-gray-200 bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">규칙 편집</h2><button onClick={close} className="text-sm text-gray-400">닫기</button></div><div className="mt-5 grid gap-4">
  <div className="grid grid-cols-2 gap-3"><Select label="자료" value={rule.source_type} onChange={(v)=>field("source_type",v)} options={[["BANK","은행"],["CARD","카드"]]} /><Select label="대상" value={rule.match_field} onChange={(v)=>field("match_field",v)} options={[["COUNTERPARTY","거래처"],["DESCRIPTION","내용"]]} /></div>
  <Select label="일치 방식" value={rule.match_operator} onChange={(v)=>field("match_operator",v)} options={[["EXACT","정확히 일치"],["CONTAINS","문구 포함"]]} /><label className="text-sm font-medium">기준 문구<input value={rule.match_value} onChange={(e)=>field("match_value",e.target.value)} className="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2 font-normal" /></label>
  <Select label="거래유형" value={rule.transaction_type} onChange={(v)=>field("transaction_type",v)} options={TYPES} /><Select label="대분류" value={rule.category_l1??""} onChange={(v)=>{field("category_l1",v||null);field("category_l2",null);}} options={[["","미분류"],...roots.map((c)=>[c.name,c.name])]} /><Select label="소분류" value={rule.category_l2??""} onChange={(v)=>field("category_l2",v||null)} options={[["",rule.category_l2&&!children.some((c)=>c.name===rule.category_l2)?rule.category_l2:"선택 안 함"],...children.map((c)=>[c.name,c.name])]} />
  <div className="grid grid-cols-2 gap-3"><Select label="고정/변동" value={rule.fixed_variable??""} onChange={(v)=>field("fixed_variable",v||null)} options={[["","선택 안 함"],["FIXED","고정"],["VARIABLE","변동"]]} /><Select label="필수/선택" value={rule.essential_optional??""} onChange={(v)=>field("essential_optional",v||null)} options={[["","선택 안 함"],["ESSENTIAL","필수"],["OPTIONAL","선택"]]} /></div>
  <label className="flex items-center justify-between border-t border-gray-100 pt-4 text-sm font-medium">규칙 활성화<input type="checkbox" checked={rule.is_active} onChange={(e)=>field("is_active",e.target.checked)} /></label><button onClick={()=>void save(rule)} className="rounded-lg bg-gray-900 px-4 py-3 text-sm font-semibold text-white">변경사항 저장</button></div></div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[][]}){return <label className="text-sm font-medium">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-gray-300 bg-white px-3 py-2 font-normal">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
